### ISSUE TITLE
How to modify the red box icon in the topdown map?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#10]
How to modify the red box icon in the topdown map?
![image](https://user-images.githubusercontent.com/34536352/95946641-8dc1de80-0e1f-11eb-8b6c-31852c92838f.png)

**Comment by yyf17** [comment]
How to add one or more green circles to the topdown map, the geographic coordinates of these circles are given, for example (1.390355, -1.5434817, 3.183166)，The drawing effect is shown below
![image](https://user-images.githubusercontent.com/34536352/95959978-c40a5880-0e35-11eb-9eb4-95648110e815.png)

My version of habitat_sim is v0.1.5, and the version of habitat is v0.1.5.
Thanks a lot

**Comment by ChanganVR** [comment]
Hi Yinfeng, 

The top down map is plotted in Habitat lab, please take a look at this file: https://github.com/facebookresearch/habitat-lab/blob/7c4286653211bbfaca59d0807c28bfb3a6b962bf/habitat/utils/visualizations/maps.py#L92-L184

I suggest you to ask this type of questions directly in Habitat lab. They might have better answers for you.
