### ISSUE TITLE
av_wan with distractor sounds checkpoint, config yaml and splits

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [facebookresearch/sound-spaces#102]
Hi Changan,

Could you share the heard.pth checkpoint that was trained in the distractor sound environment? Additionally, could you share the config file and the splits used for training and evaluation in this task?

Thank you

**Comment by ChanganVR** [comment]
As I mentioned earlier in the meeting I don't have the checkpoint for this anymore. Closing the issue now.
