### ISSUE TITLE
Access to inside of Soundspaces 2.0 audio simulator

### ISSUE THREAD

**Issue by dlsah915** [facebookresearch/sound-spaces#106]
Hi, @ChanganVR !

Thank you for the great work! (Soundspaces 2.0)
I'm very impressed by your state-of-the-art acoustic simulator.
So, how did you build for diffraction simulation on Soundspaces 2.0?
I already read Carl's paper related to Soundspaces 2.0, but what I want to know is the availability of code for diffraction in Soundspaces 2.0.

Best Regards,

**Comment by ChanganVR** [comment]
Hi @dlsah915, thank you for your interest in the work. Carl implemented the diffract based on his paper (cited in SS 2.0). However, we don't have the plan to release the source code, but this feature can be enabled in the simulation by setting diffraction to true. Let me know if you have other questions.

**Comment by dlsah915** [comment]
Thank you for your prompt response! Your explanation has helped me comprehend the matter better.
