### ISSUE TITLE
Embodiment Constraints Calculation

### ISSUE THREAD

**Issue by krantiparida** [facebookresearch/sound-spaces#11]
From the paper, it is clear that the receiver can not go into every location in the scene. So, some of the points that are not navigable are removed from the dataset. At which point is the calculation done for the navigable points (I am unable to figure this out from the file `scripts/cache_observations.py`)? or is it precomputed and saved in the `graph.pkl` file of every scene?

**Comment by ChanganVR** [comment]
Hi there, the navigable points are precomputed and saved in the graph.pkl file. Points.txt file contains all the sampled points, and basically you can call the habitat function sim.is_navigable() to check if a point is navigable. I compute the graph based on the navigability of points.

**Comment by krantiparida** [comment]
Thanks, Changan for the clarification.

**Comment by sreeharshaparuchur1** [comment]
@ChanganVR ,

apologies on bothering you with an issue over two years old. I wanted to understand in further detail what data is given by the points.txt and graph.pkl files. I have plotted the points points.txt file for several scenes and the results look similar to this: 
![image](https://user-images.githubusercontent.com/43914425/211525469-53f1a28e-a57f-4a40-af6a-39a10dbfbb19.png)

The 'X's near the bottom of the map can be ignored as they indicate the locations of the 'viewpoints' as specified in the corresponding SAVI split.

I am confused as to why there are nodes at places other than the navigable points as indicated by the top-down map (indicated by having a coloured dot above a 'white' masked object). I understand that this may have something to do with the height of the object classes which is something I'd like to clarify with you. the above top-down map was plotted at the height given by the agent's start_coordinate.

**Comment by ChanganVR** [comment]
@sreeharshaparuchur1 basically, when the SoundSpaces 1.0 data was first simulated, it was rendered for offline use and we wanted to ensure the action space consistent, so we had to sample a grid for each environment and render RIRs for all points of the grid points. The navigability check was done later to remove invalid points.

So in a nutshell, points.txt file includes all grid points while graph.pkl contains connected points where the agent could move in between points.

**Comment by sreeharshaparuchur1** [comment]
@ChanganVR , that explanation is consistent with the results that I have observed on analysis of the dataset. Thank you!
