### ISSUE TITLE
Multiple sound sources and goal locations

### ISSUE THREAD

**Issue by kksinghal** [facebookresearch/sound-spaces#116]
Hello,
I want to create a custom environment where I want to add multiple sound sources (with different sounds) and set those as goals. But I couldn't find the code that initialises the sound source position and sets that position as a goal. Also, what changes will I need to make to do that? 

Thanks
Kartik

**Comment by ChanganVR** [comment]
For SS 1, it's essentially setting the index for source/reciever and retrieving the corresponding RIR, for which, you can check out the function here: https://github.com/facebookresearch/sound-spaces/blob/3768a5073fb305723676b07cb2a78b62f0d7f6c6/soundspaces/simulator.py#L478

For SS 2 (on the fly rendering), you can check out the tutorial here: https://github.com/facebookresearch/sound-spaces/blob/main/examples/soundspaces2_quick_tutorial.ipynb

**Comment by kksinghal** [comment]
@ChanganVR Thanks for the info. Sorry, I was struggling with installation earlier, so I couldn't respond before. But, they are solved.

I would like to change the current code for my purpose. I changed [soundspaces/datasets/audionav_dataset.py](soundspaces/datasets/audionav_dataset.py) and added two goal positions https://github.com/facebookresearch/sound-spaces/blob/3768a5073fb305723676b07cb2a78b62f0d7f6c6/soundspaces/datasets/audionav_dataset.py#L153 And I also checked in the environment object that it shows two goals. However, in the terminal log, it seems that only one goal (first one) is being used to initialise the sound source, and I also receive the observations (based on the GPS compass) according to that one goal only. I suppose that habitat supports only 1 goal scenario (https://github.com/facebookresearch/habitat-lab/issues/735#issuecomment-929389560), but I will be able to solve the purpose if I can add the sound sources at the multiple goal locations, then I will write the metrics code myself. 

Are there any other changes that are required?

@dosssman Your issue discussions with Changan have been very useful. Please share your knowledge as well.
Thanks All.

**Comment by kksinghal** [comment]
Also, sorry if the following question is trivial. If we have multiple sound source locations, can I call 
`audio_sensor.setAudioSourceTransform(source_pos + np.array([0, 1.5, 0])) # add 1.5m to the height calculation 
` 
(taken from examples/soundspaces2_quick_tutorial.ipynb) multiple times (say 2) for different positions to add two sound sources. If this can be done, then my issue is solved. Thanks

**Comment by kksinghal** [comment]
Asnwers are here https://github.com/facebookresearch/sound-spaces/issues/84#issuecomment-1397860379. and https://github.com/facebookresearch/sound-spaces/issues/86#issuecomment-1210060378 Thanks
