### ISSUE TITLE
How to generate continuous audio

### ISSUE THREAD

**Issue by 310mo** [facebookresearch/sound-spaces#124]
I have a question about how to generate continuous sounds in SoundSpaces 2.0.

In `sound-spaces/soundspaces/continuous_simulator.py`, the function `crossfade` seems to be in charge of smoothly connecting the sound at one point to the sound at the next point.
However, `crossfade` is only applied to the first 50 ms (`int(0.05 * sr)`).
Is this a value specific to the default one-step sound length of 250 ms (`config.TASK_CONFIG.SIMULATOR.STEP_TIME = 0.25`)?
Or can `crossfade` be applied as is for any step length?

**Comment by ChanganVR** [comment]
@310mo yes, it certainly depends on how far away the consecutive points are (not only the time) since the acoustics for different points in the space are different. I don't think there is an optimal value for the fading time and you can tune this value to suit your need and application.

**Comment by 310mo** [comment]
Thank you very much for your reply.
I close this issue.
