### ISSUE TITLE
"python examples/minimal_example.py" Error 

### ISSUE THREAD

**Issue by Wind-Wing** [facebookresearch/sound-spaces#126]
Install success following `INSTALLATION.md`.
`python setup.py install --audio --headless` in Ubuntu 22.04 with AMD cpu

But `python examples/minimal_example.py` shows
`python: Relink '/home/$USER/anaconda3/envs/ss/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg/habitat_sim/_ext/libRLRAudioPropagation.so' with '/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol 'crc32_z'
`
The same error occurred when I tried to import habitat_sim in python terminal. This problem is also mentioned in #123.

Can anyone help? :)

**Comment by Wind-Wing** [comment]
The same error when I tried to `import habitat_sim` in python terminal.
This problem is also mentioned in #123

**Comment by hhhuxy** [comment]
Could u tell me how u resolved it? I've encountered the exactly the same situation
