### ISSUE TITLE
version `GLIBC_2.29' not found

### ISSUE THREAD

**Issue by EntyccE** [facebookresearch/sound-spaces#129]
After I followed the installation guide, I started to run example commands in readme and ran into the following error:
```
ImportError: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by .../anaconda3/envs/ss/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg/habitat_sim/_ext/libRLRAudioPropagation.so)
```

I searched a lot but I didn't managed it. Can I get any help?

**Comment by EntyccE** [comment]
My version is `ldd (GNU libc) 2.28`

**Comment by ChanganVR** [comment]
@EntyccE you can find the solution here: https://github.com/facebookresearch/rlr-audio-propagation/issues/9#issuecomment-1317697962

**Comment by EntyccE** [comment]
@ChanganVR Thanks a lot! So sorry that I didn't notice the specific insturction part.
