### ISSUE TITLE
semantic label to acoustic material mapping

### ISSUE THREAD

**Issue by krantiparida** [facebookresearch/sound-spaces#13]
Hi, Changan. As per the paper, 
"For each semantic class that was deemed to be acoustically relevant, we provide a mapping to an equivalent acoustic material from an existing material database. For the floor, wall, and ceiling classes, we assume acoustic materials of carpet, gypsum board, and acoustic tile, respectively."

It would be really helpful if you can kindly provide the mapping for all the semantic labels.

Thanks in advance.

**Comment by ChanganVR** [comment]
Hi Kranti,

Yes, the material mapping file is added to the scripts folder.

Changan

**Comment by krantiparida** [comment]
Thanks, Changan.

**Comment by rfalcon100** [comment]
@ChanganVR Regarding this question, I've noticed that there are some semantic labels that are not mapped to an acoustic material, at least for the Replica dataset. For example the class  `class_id=61, class_name='pillow'` is not mapped to a material in your provided script.

Are these classes ignored? Or is there a separate mapping for Replica?

**Comment by ChanganVR** [comment]
@rfalcon100 is pillow in the category of objects? I think for objects that do not have explicit mapping, we are using the default material: https://github.com/facebookresearch/sound-spaces/blob/deb41f4e3ba64f9bae325c1eb091489465c1c551/res/Material%20Map.txt#L255-L261
