### ISSUE TITLE
Relink '.../libRLRAudioPropagation.so' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z''

### ISSUE THREAD

**Issue by hhhuxy** [facebookresearch/sound-spaces#147]
When I followed the instructions of installation step by step, and it seems to be installed successfully, the final outputs:
````
Using /home/user/miniconda3/envs/ss/lib/python3.9/site-packages/setuptools/_vendor
Finished processing dependencies for habitat-sim==0.2.2
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
Processing ./build/deps/magnum-bindings/src/python
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: magnum
  Building wheel for magnum (setup.py) ... done
  Created wheel for magnum: filename=magnum-0.0.0-cp39-cp39-linux_x86_64.whl size=58190268 sha256=c688e090dad7237494a1b5b95a4649cc9447f2603797dfce292c071ffd008483
  Stored in directory: /tmp/pip-ephem-wheel-cache-axbt2t4z/wheels/f2/f2/46/7aebb35c1f94a8ac5997460c1b3c4b293f1d3a92af5749a150
Successfully built magnum
Installing collected packages: magnum
Successfully installed magnum-0.0.0
````

> before that, I manually installed `scipy==1.13.0` because of the occurrence of the following error:
> ![bug2](https://github.com/user-attachments/assets/8580d0c1-967b-4ec6-ae18-2d333d117413)

After that, I tried to import it in the terminal:
````
python
import habitat_sim
````

It went wrong with 
````
python: Relink `/home/user/miniconda3/envs/ss/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg/habitat_sim/_ext/libRLRAudioPropagation.so' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
free(): invalid pointer
Aborted (core dumped)
````

------

I have noticed the same problem in [#issue126](https://github.com/facebookresearch/sound-spaces/issues/126) and [#issue123](https://github.com/facebookresearch/sound-spaces/issues/123). I have then restarted an installation by installing `numpy` and `numba` first manually with:
````
pip install numpy==1.23
pip install numba==0.58
````

However, the problem remains. And different from [#issue123](https://github.com/facebookresearch/sound-spaces/issues/123), I've got no other version warnings.
![import_error](https://github.com/user-attachments/assets/09b6192c-bb2f-4ecf-919b-5bde6103ba97)

I've also checked issues in `habitat-sim` git repo, but failed to find similar problem.

Here's my package version:
````
Package             Version
------------------- -----------
attrs               24.2.0
autocommand         2.2.2
backports.tarfile   1.2.0
certifi             2024.7.4
charset-normalizer  3.3.2
contourpy           1.3.0
cycler              0.12.1
fonttools           4.53.1
gitdb               4.0.11
GitPython           3.1.43
habitat_sim         0.2.2
idna                3.8
imageio             2.35.1
imageio-ffmpeg      0.5.1
importlib_metadata  8.0.0
importlib_resources 6.4.0
inflect             7.3.1
jaraco.context      5.3.0
jaraco.functools    4.0.1
jaraco.text         3.12.1
kiwisolver          1.4.5
llvmlite            0.41.1
magnum              0.0.0
matplotlib          3.9.2
more-itertools      10.3.0
numba               0.58.0
numpy               1.23.0
numpy-quaternion    2023.0.4
ordered-set         4.1.0
packaging           24.1
pillow              10.4.0
pip                 24.2
platformdirs        4.2.2
pyparsing           3.1.4
python-dateutil     2.9.0.post0
requests            2.32.3
scipy               1.13.0
setuptools          72.1.0
six                 1.16.0
smmap               5.0.1
tomli               2.0.1
tqdm                4.66.5
typeguard           4.3.0
typing_extensions   4.12.2
urllib3             2.2.2
wheel               0.43.0
zipp                3.19.2
````
and I'm using ubuntu 20.04

Please could u help me?

**Comment by hhhuxy** [comment]
So sorry to bother u, I succeeded in installing it and importing it now (maybe).

To others who might encounter this, there's no need to install `numpy` and `numba` manually, and i solved the problem **by `import habitat` before `import habitat_sim`.**

However i have completely no idea why `import habitat-sim` first will cause the error, it behaves similar to [an issue in pytorch repo](https://github.com/pytorch/pytorch/issues/19739), though neither `open3d` nor `pytorch` is explicitly imported. 

The strange thing is, for the following simple script `test.py`:
````python
import habitat
import habitat_sim

print(habitat_sim.__file__)
````
it works fine, but if `import habitat_sim` before `import habitat`, the previous error
````
python: Relink `/home/user/miniconda3/envs/ss/lib/python3.9/site-packages/habitat_sim-0.2.2-py3.9-linux-x86_64.egg/habitat_sim/_ext/libRLRAudioPropagation.so' with `/lib/x86_64-linux-gnu/libz.so.1' for IFUNC symbol `crc32_z'
````
occurs again.

Same in terminal.

![strangeThing](https://github.com/user-attachments/assets/24f051c8-74f1-40d2-b379-f86de5d7bc17)

If anyone knows the reason, i'll be thankful if u would tell me.

**Comment by wang123zhao551451** [comment]
Thanks for your hard work on this bug !
