### ISSUE TITLE
No file "mp3d.scene_dataset_config.json"

### ISSUE THREAD

**Issue by Star-down** [facebookresearch/sound-spaces#148]
I used the -- habitat parameter when downloading the MP3D dataset. After downloading, it seems that my file is missing the data/scene_datasets/mp3d/mp3d.scene_dataset_config.json file. Has anyone encountered the same problem? Would anyone be willing to share this file with me?

**Comment by hhhuxy** [comment]
You can find it [here](https://github.com/facebookresearch/habitat-sim/blob/RLRAudioPropagationUpdate/DATASETS.md).
Search for `SceneDatasetConfig` in the page.

**Comment by Star-down** [comment]
@hhhuxy Thank you!I got it!
