### ISSUE TITLE
Question about Continous audio-visual navigation benchmark

### ISSUE THREAD

**Issue by hhhuxy** [facebookresearch/sound-spaces#149]
@ChanganVR Hi, thank you for the great work!
I noticed in the SoundSpaces 2.0 paper, specifically in Table 3, a benchmark for continuous audio-visual navigation is provided. Could you please share the parameter files for the benchmark model as well as the evaluation scripts?

Additionally, I observed that when training using the script `python ss_baselines/av_nav/run.py --exp-config ss_baselines/av_nav/config/audionav/mp3d/train_telephone/audiogoal_depth_ddppo.yaml --model-dir data/models/ss2/mp3d/dav_nav CONTINUOUS True` as suggested in **Training continuous navigation agent**, the agent's action space still consists of only moving forward 1 meter, turning left/right 90 degrees, and issuing a stop action. Is this correct? If so, does it correspond to the DAV-Nav model described in Section 5.3, third paragraph of the paper?

My understanding is that the results in Table 3 reflect the performance of DAV-Nav. If this is the case, how are the continuous space and continuous sound reflected? Also, are there runnable scripts available for the continuous AV-Nav task mentioned in Section 5.3, second paragraph of the paper?

I am currently attempting to reproduce the benchmark model’s performance and would greatly appreciate your assistance.

Thank you in advance for your help.

**Comment by ChanganVR** [comment]
Hi @hhhuxy thanks for the interest. We don't have the pretrained files anymore. To reproduce the benchmark, you would need to train the model from scratch with the config files.

The action space is set not in config file but here: https://github.com/facebookresearch/sound-spaces/blob/287184fd7067a0385558492716355c54875500ee/ss_baselines/av_nav/config/default.py#L216-L223

**Comment by hhhuxy** [comment]
Thank you for the reply, I understand now.
