### ISSUE TITLE
The horizontal axis of validation curve is checkpoint index, is this true?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#15]
The horizontal axis of validation curve is checkpoint index, is this true?
The validation curve is as follows:
![image](https://user-images.githubusercontent.com/34536352/97965494-6a25fe80-1df5-11eb-9739-3989203e4d5c.png)

**Comment by ChanganVR** [comment]
Hi Yifeng, yes the x-axis is the checkpoint number.
