### ISSUE TITLE
Given a starting position and an action (for example: HabitatSimActions.MOVE_FORWARD), how to get the target position?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#17]
In soundspace,
Given an action (for example: HabitatSimActions.MOVE_FORWARD), how to get the offset of x, y, z?
Or Given a starting position and an action (for example: HabitatSimActions.MOVE_FORWARD), how to get the target position?

**Comment by ChanganVR** [comment]
Please refer to these lines of code for the target position calculation: https://github.com/facebookresearch/sound-spaces/blob/bff9e1b32037da7c820826593ef565691c70fb0d/soundspaces/simulator.py#L268-L278

If you have more specific question, please let me know.

**Comment by yyf17** [comment]
Thank you, your suggestion is very good, I will implement it according to your ideas.
