### ISSUE TITLE
self._audiogoal_cache is increasing all the time

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#18]
in the file   soundspaces/simulator.py, the code below may have a problem about memory 
![image](https://user-images.githubusercontent.com/34536352/98881785-c78d1000-24c5-11eb-8c7f-0d0df63b30c8.png)
During the execution of the program, I found that the variable ***self._audiogoal_cache[join_index]*** is increasing. I know that a task experiment is over. Is there any way to clean this up and ensure that an epsisode is saved. It is cleared every time an episode is updated. I wonder if the idea is reasonable?

**Comment by ChanganVR** [comment]
Cache is used to speed up the computation by saving the computed waveforms at the cost of memory usage. And it resets every time the scene environment changes to ensure the memory usage is bounded. I didn't observe a huge memory usage when I ran the code. If memory is the constraint for you, you can simply disable cache by always computing and returning the current audiogoal.

**Comment by yyf17** [comment]
Thank you, maybe the large memory is caused by other reasons, I will check it.
