### ISSUE TITLE
Why do we need to sleep for 2 seconds when evaluate multiple checkpoints in order?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#19]
in the code file "av_nav/common/base_trainer.py"
```
                # evaluate multiple checkpoints in order
                while True:
                    current_ckpt = None
                    while current_ckpt is None:
                        current_ckpt = poll_checkpoint_folder(
                            self.config.EVAL_CKPT_PATH_DIR, prev_ckpt_ind, eval_interval
                        )
                        time.sleep(2)  # sleep for 2 secs before polling again
                    logger.info(f"=======current_ckpt: {current_ckpt}=======")
```
Why do we need to sleep for 2 seconds evaluate multiple checkpoints in order? In this case, the program will run longer.

![image](https://user-images.githubusercontent.com/34536352/99245660-f2cb7400-27d1-11eb-9366-02e76f450dad.png)

**Comment by ChanganVR** [comment]
This is meant for running validation along with training since checkpoints are saved to the disk infrequently. 

I recommend this way as well. You should run one job for training and one job in parrallel for evaluation.

**Comment by yyf17** [comment]
Thank you.
