### ISSUE TITLE
on the shape of variable observation_space.spaces['audiogoal']

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#20]
### 2) In the code file :scripts/interactive_demo.py,  we can get observation_space from following code
···
        observation_space = None
        if observation_space is None:
            observation_space = env.observation_space
···
### 3) In the code file :av_nav/rl/models/audio_cnn.py,  Through following code
```
 observation_space.spaces['audiogoal'].shape[2],
```
I found that observation_space.spaces['audiogoal'].shape should be at least 3 dimensions.
![image](https://user-images.githubusercontent.com/34536352/99348066-9cdef500-28d3-11eb-8a3d-1071a975187b.png)
### 4) In the code file :av_nav/rl/models/audio_cnn.py,  Through following code
```
    def forward(self, observations):
        cnn_input = []

        audio_observations = observations[self._audiogoal_sensor]
        # permute tensor to dimension [BATCH x CHANNEL x HEIGHT X WIDTH]
        audio_observations = audio_observations.permute(0, 3, 1, 2)
        cnn_input.append(audio_observations)

        cnn_input = torch.cat(cnn_input, dim=1)

        return self.cnn(cnn_input)

```
I found that  observation_space.spaces['audiogoal'].shape  should be 4 dimensions.
### 5) how do I construct observation_space.spaces['audiogoal'] in the  code file :scripts/interactive_demo.py,
Can you give me some suggestions? I wrote some code, and the following errors are included at runtime:
···
 self._n_input_audio = observation_space.spaces[audiogoal_sensor].shape[2]
IndexError: tuple index out of range
···

![image](https://user-images.githubusercontent.com/34536352/99348356-5fc73280-28d4-11eb-8301-c885f6604977.png)

**Comment by ChanganVR** [comment]
There are two representations of the audio signal. The first one is the raw audio signal (audiogoal) and the second one is spectrogram. And the shape of them are (2, 44100), (65, 65, 2) for replica and (2, 16000), (65, 26, 2) for mp3d. The additional dimension in your example 4 is the batch size. 

The input to AudioCNN is the spectrogram, which has 4 dimensions including the batch size dimension. The audiogoal sensor is only used for rendering the video now.

**Comment by yyf17** [comment]
Thank you very much.
