### ISSUE TITLE
on validation

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#21]
1) NUM_PROCESSES is set to 1 during verification (evaluating each checkpoint and generating a verification curve), but it is set to 5 during training. Why is this parameter different during verification? Is NUM_PROCESSES recommended to be changed to 5 when verifying (evaluating each checkpoint and generating a verification curve)?
2) About evaluate multiple checkpoints in order
2. 1) There is an infinite loop in the ‘eval’ function in av_nav/common/base_trainer.py. Will this cause the verification process to not end?
2. 2) There is also a sleep for 2 secs before polling again (time.sleep(2), I have asked this question last time). Is this statement recommended not to be executed?
![image](https://user-images.githubusercontent.com/34536352/99924476-6e4e9780-2d75-11eb-9dd4-6e6c54e9f160.png)

2. 3) The verification log is still very large (I have consulted this question last time), the sentence in the log record "=======current_ckpt: data/models/replica/audiogoal_depth/data /ckpt.xxx.pth=======” Will repeat xxx times, this xxx is from 1 to 800, I have not found the reason for this phenomenon, can you give some suggestions?
![image](https://user-images.githubusercontent.com/34536352/99924505-8e7e5680-2d75-11eb-8e98-017010fd8f5f.png)

**Comment by ChanganVR** [comment]
The logic behind the evaluation design is to run evaludation parallelly with the training and usually evaluation runs faster than training so that's why using one process is enough. You can set it to a larger number if you want. And you need to manually kill the evaluation process after it finishes as it keeps polling the directory.

**Comment by JeremyLinky** [comment]
> The logic behind the evaluation design is to run evaludation parallelly with the training and usually evaluation runs faster than training so that's why using one process is enough. You can set it to a larger number if you want. And you need to manually kill the evaluation process after it finishes as it keeps polling the directory.

When I set a larger number, like 9,  It won't test or eval all the episodes in testing/evaluating JSON files. I wonder why could this happened. Looking forward to your reply!!

**Comment by ChanganVR** [comment]
Oops. Sorry for just seeing this comment @JeremyLinky. I think I have answered your question in another thread #22.
