### ISSUE TITLE
The validation did not stop,but suspend.

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#23]
The pring information shows that the validation  experiment has printed and verified the check point of ckpt.799.pth, but the main program has been stopped there without termination.
#### the check point of ckpt.799.pth
![image](https://user-images.githubusercontent.com/34536352/100064692-d08ac380-2e6d-11eb-9f4a-fc38b65df5cc.png)

#### The validation did not stop,but suspend.
![image](https://user-images.githubusercontent.com/34536352/100064781-e7c9b100-2e6d-11eb-9d5c-3635f4819982.png)

**Comment by ChanganVR** [comment]
It keeps polling new checkpoints in the directory. You need to manually kill it after it evaluates all checkpoints.

**Comment by JeremyLinky** [comment]
> It keeps polling new checkpoints in the directory. You need to manually kill it after it evaluates all checkpoints.

Hi, Changan, in validation,  is validation curve plot in tensorboard or somewhere else?

**Comment by yyf17** [comment]
thank you @ChanganVR

**Comment by ChanganVR** [comment]
@JeremyLinky The validaiton stats are saved in the tensorboard log files under the tb/ folder. You can visualize it with tensorboard.
