### ISSUE TITLE
How to collect all agent states in Matterport?

### ISSUE THREAD

**Issue by Pixie412** [facebookresearch/sound-spaces#25]
Hi,
I am wondering how to get all agent states in Matterport (i.e. rgb and depth images from all navigable points, each with 4 directions).

**Comment by ChanganVR** [comment]
Check out scripst/cache_observations.py, that's what that script does exactly.

**Comment by Pixie412** [comment]
Yes, thank you very much! I have another question regarding the size of agent observation in a new issue. If it doesn't bother you, could you please provide some suggestion?

**Comment by Pixie412** [comment]
Thanks!
