### ISSUE TITLE
Initial Run & Speed-up

### ISSUE THREAD

**Issue by czha5168** [facebookresearch/sound-spaces#26]
Hi Changan,

I am new to this interesting repo and would like to make a few quick enquires if possible. Thanks in advance for your time.

1. When running "python av_nav/run.py --exp-config av_nav/config/replica/train_telephone/audiogoal_depth.yaml --model-dir data/models/replica/audiogoal_depth", I noticed some middle message like "Current scene: frl_apartment_3 and **sound: None**". Does it indicate no sound is utilized for the AudioNav task? Is it a normal case as we expected so?

2. **(closed - see below)** Could you pls also leave some comments & guidances about speeding up the training process? I am using all default settings, and it's shown as "env-time: 26.767s  pth-time:154.669s frames: 8250".

Looking forward to your replied and best wishes

**Comment by czha5168** [comment]
Update: 
pth-time is training time, which could be reduced by compiling habitat-smi with CUDA support. The suitable habitat-repos can be cloned as follows:
git clone --single-branch --branch objectnav_ddppo_agent https://github.com/facebookresearch/habitat-lab.git
git clone --single-branch --branch submodule-instructions https://github.com/facebookresearch/habitat-sim.git

**Comment by ChanganVR** [comment]
Hi Chaoyi,

For your first question, that message is generated when the code obtains all the scenes in the dataset and it builds a dummy dataset. Check out this line for more detail: https://github.com/facebookresearch/sound-spaces/blob/bff9e1b32037da7c820826593ef565691c70fb0d/av_nav/common/env_utils.py#L40

It's weird that your GPU training time is longer than env-time. Usually the former takes more time. I would suggest you to first check if you have the correct version of pytorch installed. And I found incorrect pytorch version (matching CUDA version) significantly slowed down the training. As for multi-GPU training, I'll point you to the DD-PPO implementation (https://github.com/facebookresearch/habitat-lab/tree/master/habitat_baselines/rl/ddppo) in Habiat, which utilizes multi-gpus and speeds up training.

**Comment by czha5168** [comment]
Many thanks Changan! I will have a close study on it.
