### ISSUE TITLE
Why FORWARD_STEP_SIZE and GRID_SIZE are not the same in the data set replica?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#27]
By printing the running configuration information, I found FORWARD_STEP_SIZE and GRID_SIZE are not the same in the data set replica, They are the following data：
```
FORWARD_STEP_SIZE: 0.25
GRID_SIZE: 0.5.

```
![image](https://user-images.githubusercontent.com/34536352/100971859-ae322d80-3572-11eb-9f15-5b9a56716f90.png)
![image](https://user-images.githubusercontent.com/34536352/100971912-ca35cf00-3572-11eb-86aa-dab659b29a71.png)

Why FORWARD_STEP_SIZE and GRID_SIZE are not the same in the data set replica?

**Comment by ChanganVR** [comment]
The FORWARD_STEP_SIZE parameter is actually not being used since the agent moves on a grid of fixed resolution. But I'll update the repo to make it consistent. The step size is 0.5m for Replica.

**Comment by yyf17** [comment]
Thanks.
