### ISSUE TITLE
How can I change the size of agent observations?

### ISSUE THREAD

**Issue by Pixie412** [facebookresearch/sound-spaces#28]
Hi,
The scripts/cache_observations.py only provide 128*128 resolution rgb and depth images. Is there any way that I can get other resolution observations? In the habitat-sim, I can change the ImageExtractor() input setting of "img_size", but I don't know how to do it in soundspaces. Can you provide any suggestions? 
![image](https://user-images.githubusercontent.com/72333326/101773583-f380cd00-3b27-11eb-8124-99832efb512a.png)

**Comment by Pixie412** [comment]
I changed '_C.DISPLAY_RESOLUTION = 140' in the av_nav/config/default.py, but it still generates 128*128 resolution. What should I do?

**Comment by ChanganVR** [comment]
Hi, the default values are always overwritten by config files. This script reads "av_nav/config/replica/train_telephone/pointgoal_rgb.yaml'" as input, which reads task config "configs/replica/pointgoal.yaml". To change the sensor resolution, you need to modify these lines: https://github.com/facebookresearch/sound-spaces/blob/bff9e1b32037da7c820826593ef565691c70fb0d/configs/replica/pointgoal.yaml#L6-L11

**Comment by Pixie412** [comment]
It works! Thanks a lot!
