### ISSUE TITLE
how to write a habitat.config  to *.yaml file?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#29]
how to write a habitat.config  to *.yaml file?

**Comment by yyf17** [comment]
```
    with open('config.yaml', 'w') as f:
        config = yaml.dump(config, stream=f,default_flow_style=False, sort_keys=False)
```
it makes a wrong when the value is a dict:
![image](https://user-images.githubusercontent.com/34536352/101978925-c2251000-3c93-11eb-8f63-3cfcbe683101.png)

the origin is 
![image](https://user-images.githubusercontent.com/34536352/101978909-ab7eb900-3c93-11eb-8609-1c8969d6e5aa.png)

**Comment by ChanganVR** [comment]
I haven't tried that, but you could look into [yacs](https://github.com/rbgirshick/yacs) (the config library Habitat uses) to see if it provides such functionality.

**Comment by yyf17** [comment]
thank you.
