### ISSUE TITLE
Questions about point goal navigation.

### ISSUE THREAD

**Issue by JeremyLinky** [facebookresearch/sound-spaces#31]
Hi, Changan! Is it the truth that the agent still needs to predict a stop action to stop the current episode in point goal task? Why can't I just stop when the (delta x, delta y) is equal to (0,0) ?

**Comment by ChanganVR** [comment]
We were just following what the pointgoal nav baseline did, predicting an action regardless of the input. 

"stop when the (delta x, delta y) is equal to (0,0)" only works when the navigation graph is discrete like this environment. And in addition, I think it might be easy for the agent learn to stop when the input is (0, 0), althought I haven't tested.

**Comment by JeremyLinky** [comment]
> We were just following what the pointgoal nav baseline did, predicting an action regardless of the input.
> 
> "stop when the (delta x, delta y) is equal to (0,0)" only works when the navigation graph is discrete like this environment. And in addition, I think it might be easy for the agent learn to stop when the input is (0, 0), althought I haven't tested.

Thanks for your patience!!
