### ISSUE TITLE
Question about evaluating.

### ISSUE THREAD

**Issue by JeremyLinky** [facebookresearch/sound-spaces#32]
Hi, Changan, when you run on  'eval' or 'test' mode, do you need to use ".eval()" after the model? If you used this in  'eval' or 'test' mode, where is it?

**Comment by ChanganVR** [comment]
I don't think I used eval(), as it is mostly used for dropout, batchnorm and etc. Since the model didn't have these components. It was not critical to use eval().

**Comment by JeremyLinky** [comment]
> I don't think I used eval(), as it is mostly used for dropout, batchnorm and etc. Since the model didn't have these components. It was not critical to use eval().

Thanks for replying!
