### ISSUE TITLE
Questions about sound source of  Matterport3D.

### ISSUE THREAD

**Issue by JeremyLinky** [facebookresearch/sound-spaces#33]
Hi,Changan. The sampling rate for Replica is 44.1 kHz whereas matterport is 16 kHz, and there are 2 questions I have:
1、Is the generating of binaural_rirs data related to the 1s source sound?
2、If the answer of question 1 is true, then which frequency of source sound is used to generate the binaural_rirs data of Matterport3D ? 44.1kHz or 16kHz?
 
Besides, in other paper of Facebook research named VisualEcho, if we want to generate echo data of Matterport3D dataset,  should the FREQ be changed as 16000? Here is the related codes in getEchoes.py of VisualEcho :
https://github.com/facebookresearch/VisualEchoes/blob/master/getEchoes.py

**Comment by ChanganVR** [comment]
Hi Jeremy, the frequency of the source sound should be the same as the frequency of the room impulse response. The reason why MP3d has 16k while replica has 44.1k sampling rate is that MP3D takes much more space so we downsampled its RIR.

Whenever you use MP3D, sample the source sound to 16k.

**Comment by czha5168** [comment]
Hi Changan,

Thanks for the detailed clarification about sampling frequency on MP3D. I wonder the transformation of the source sound (from 44.1k to 16k - to make it compatible on MP3D) could be simply achieved by Ruohan's code here (https://github.com/facebookresearch/VisualEchoes/blob/1c2dbf4300fe4f8294b7435e510dd5e2d56ff7d2/getEchoes.py#L29) by assigning FREQ with 16k. Much appreciated.

**Comment by ChanganVR** [comment]
Hi @czha5168, you can change the sampling rate by simply using librosa's loading function: http://man.hubwiz.com/docset/LibROSA.docset/Contents/Resources/Documents/generated/librosa.core.load.html. I guess Ruohan's code should also work. This can be achieved by any libraries.

**Comment by czha5168** [comment]
Got it and appreciate it!
