### ISSUE TITLE
About acoustic simulations

### ISSUE THREAD

**Issue by rfalcon100** [facebookresearch/sound-spaces#34]
Hi, I have a questions regarding the acoustic simulation. 

It seems that the code in `/sound-spaces/soundspaces/simulator.py` only supports loading pre-rendered BRIRs, which can be downloaded with the links provided in the documentation.

Is the acoustic simulator code available somewhere? 

Thanks

**Comment by ChanganVR** [comment]
The RIR simulation code was developed by Facebook Reality Labs, and it is Facebook's proprietary code. Currently, they don't have a plan to release the code.

**Comment by rfalcon100** [comment]
Ok, I understand.
