### ISSUE TITLE
How to generate sounds when facing a new direction except for 0, 90, 180, 230 degrees

### ISSUE THREAD

**Issue by PeihaoChen** [facebookresearch/sound-spaces#35]
Hi Changan. 

Thank you for sharing the impressive dataset. In your dataset, you have provided the RIRs for generating sounds when an agent is facing 0, 90, 180, 270 degrees. I wonder is it possible for us to generate sounds when the agent is facing other degrees (e.g. 30°)?

It would be helpful if you could provide some relevant references or code if possible.

Thanks.

**Comment by ChanganVR** [comment]
Hi Peihao,

Yes, there is a tool for converting ambisonic RIRs to binaural RIRs of any direction. I don't have access to my work laptop right now. I'll be able to do that in about 5 days.

**Comment by PeihaoChen** [comment]
Thanks for your kind reply and looking forward to the tool.

**Comment by ChanganVR** [comment]
Hi @PeihaoChen, sorry for the delay. I just added the scripts for converting ambisonic RIRs to binaural RIRs of any direction. See https://github.com/facebookresearch/sound-spaces/blob/master/scripts/ambisonic_to_binaural.py for details.

**Comment by PeihaoChen** [comment]
Thanks!!!

**Comment by AbdelrahmanYounes** [comment]
@ChanganVR Hey Changan, don't we need the ambisonic files to use this script? Is there a method that we can convert the available binaural rir to ambisonic and then use the script to get more binaural rirs for other angles?

**Comment by ChanganVR** [comment]
Hi @AbdelrahmanYounes, the directional information for other angles can only be computed with the ambisonics and you need to use ambisonics for the conversion.

**Comment by AbdelrahmanYounes** [comment]
@ChanganVR so, we can't use this script as we don't have the ambisonics, right?

**Comment by ChanganVR** [comment]
@AbdelrahmanYounes the ambisonics data can be downloaded from here: https://github.com/facebookresearch/sound-spaces/tree/master/soundspaces

**Comment by AbdelrahmanYounes** [comment]
Yes, I noticed now that the optional download option has ambisonic too. I thought at the beginning that it's only for the other binaural files. Thanks @ChanganVR
