### ISSUE TITLE
How to fetch .glb files from the release of MP3D dataset

### ISSUE THREAD

**Issue by czha5168** [facebookresearch/sound-spaces#37]
Hi Changan,

I am trying to use scripts/cache_observations.py to collect scene_observations.pkl files for some toy scenes, while the process was stuck at here https://github.com/facebookresearch/sound-spaces/blob/621a980eaa7ecdf831ba0dc329819803111e1b72/scripts/cache_observations.py#L118 (how to fetch .glb files for MP3D dataset)? Thanks for your time in advance.

**Comment by czha5168** [comment]
Never mind ... I have figured it out through habitat repo :D. Thanks~

**Comment by AaronAnima** [comment]
@czha5168 Hi, may I ask how do you solve this? I have not found the solution yet.

**Comment by joonil7** [comment]
Just in case anybody comes here with the same problem,

Downloading habitat task data of the Matterport3D dataset will solve the problem.
[https://github.com/facebookresearch/habitat-sim/blob/main/DATASETS.md#matterport3d-mp3d-dataset](url)
As from the link above, run `python download_mp.py --task habitat -o path/to/download/` and the glb files will be downloaded.

**Comment by xuai05** [comment]
@joonilna Sorry to bother you, but I encountered the following error while downloading the .glb data. Do you know how to fix it?
![image](https://github.com/facebookresearch/sound-spaces/assets/45277994/c82c77fd-e32f-48f3-a52a-68eee76ee60d)
