### ISSUE TITLE
What is the basis for dividing the number of scenes in the test data set for mp3d dataset?

### ISSUE THREAD

**Issue by JeremyLinky** [facebookresearch/sound-spaces#39]
Hi, Changan, I found that in the mp3d test dataset, some scenes have a particularly large number and some scenes have a particularly small number. Could you tell me what is the basis for dividing these numbers?

**Comment by ChanganVR** [comment]
Hi @JeremyLinky, I took the scene splits from PointNav task for Matterpor3D environments.

**Comment by JeremyLinky** [comment]
Thanks for your clarification! @ChanganVR
