### ISSUE TITLE
Is the complete download address of the SoundSpaces data set available?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#4]
Is the complete download address of the SoundSpaces data set available?
That includes the rendered sound, the original Replica-Dataset data set and the Matterport3D data set segmentation and the corresponding good data set. The Matterport3D dataset is difficult to respond to when applying.

**Comment by yyf17** [comment]
I want to download matterport3d and Replica datasets. However, 1.7T data is too large for me to download(around 10 days-time keeping 2MB/s downloading speed).

Should I download the full datasets matterport3d and Replica?

**Comment by ChanganVR** [comment]
I can't upload matterport/replica here, you should wait for the response from the matterport team.

I suggest downloading the full dataset in the background if the required disk space is affordable and you can use the partial dataset in the mean time.

**Comment by tynguyen** [comment]
Perhaps it might be useful for other people. I do not have enough space for the full data and I only want Replica. Thankfully, this is possible by using curl instead of wget. You can search for something like: 
`curl --range start-end ftp://example.com/file.ext --output test.ext`
