### ISSUE TITLE
How to generate smooth video

### ISSUE THREAD

**Issue by 310mo** [facebookresearch/sound-spaces#49]
I would like to generate a video of an agent moving in the sounding environment, and I successfully ran `scripts/intereactive_demo.py` in Replica dataset.
However, in the video generated by `scripts/intereactive_demo.py`, the agent does not move smoothly by the commands such as move forward, turn left, and turn right.
How can I generate a video where the agent moves smoothly as shown in the README (https://www.youtube.com/watch?v=4uiptTUyq30)?

**Comment by ChanganVR** [comment]
@310mo did you make sure this variable is set to True? https://github.com/facebookresearch/sound-spaces/blob/9e3318b5e54f3246a606d2373ca60e4b7efc11f1/configs/audionav/av_nav/mp3d/interactive_demo.yaml#L17

This inserts multiple visual frames between two consecutive frames so that the video looks smoother.

**Comment by 310mo** [comment]
Thank you for your reply.
I check `sound-spaces/configs/audionav/av_nav/replica/interactive_demo.yaml` (because I use Replica dataset) and `CONTINUOUS_VIEW_CHANGE` is True.

But I change some configs based on https://github.com/facebookresearch/sound-spaces/issues/44#issuecomment-869233256.
Specifically, `TASK_CONFIG.SIMULATOR.USE_RENDERED_OBSERVATIONS` is set to True and the following line is commented out.
https://github.com/facebookresearch/sound-spaces/blob/dbc587771c26b72bf0f2d41ba4a421434579bf3a/scripts/interactive_demo.py#L224

This is the example of my inplementation of `interactive_demo.py` (Some rendering isn't working well ...). Is it posssible to make demo video more smoother by provided programs?
https://youtu.be/TsyjrvTmuN0

**Comment by ChanganVR** [comment]
@310mo looks like the continuous view change does not work at all in the video. I'm not exactly sure what is wrong on your side. Does the simulator renders multiple intermediate frames between two frames? To check this, you can print out the value of this variable: https://github.com/facebookresearch/sound-spaces/blob/9e3318b5e54f3246a606d2373ca60e4b7efc11f1/soundspaces/simulator.py#L486

**Comment by 310mo** [comment]
The reason why the continuous view change does not work in my inplementation is that I have gererated the video with only
pre-rendered frames by `TASK_CONFIG.SIMULATOR.USE_RENDERED_OBSERVATIONS=True`.

However, using `interactive_demo` function in `interactive_demo.py` with `TASK_CONFIG.SIMULATOR.USE_RENDERED_OBSERVATIONS=False` does not work, probably bacause of pygame.
By using `following` function, I am able to avoid this problem (bacause pygame is not used in `following`) and succeed in generating a smooth video.
https://youtu.be/uWN33ZFDwLQ

Thank you!


And, I have another question about `interactive_demo.py`.
How can I change the sound type, sound source placement, and agent start point in this program?
This question is different from the issue, but I would appreciate it if you could answer it together.

**Comment by ChanganVR** [comment]
@310mo Sorry for the delay. The `interactive_demo.py` script currently uses the `val_telephone` data split. You will need to change the sound source location, sound type and start point in the json files of `val_telephone`. You can take a look at the `audiogoal_dataset.py` to understand how it parses the json file into episode configurations. Let me know if this works for you.

**Comment by 310mo** [comment]
Sorry for the very late reply.
I was able to change those settings freely by creating a new json file by referring to `data/datasets/audionav/replica/v1/val_telephone/val_telephone.json.gz`.

Thank you very much!
