### ISSUE TITLE
Any API to query a 3-d point's visibility?

### ISSUE THREAD

**Issue by Yushi-Du** [facebookresearch/sound-spaces#52]
Hi, I'm interested in your works. Recently, I tried to modify the baseline  "ss_baselines/av_nav/run.py", and possibly need some additional APIs to implement my method.

More specifically, I need to query a given point([x, y, z] in the world's coordinate) whether it is visible by the agent at each timestep.

However, I haven't found a feasible API for this need. Can you refer me to any related API? Any help is appreciated! Thanks :)

**Comment by ChanganVR** [comment]
Hi @Yushi-Du , for this purpose, I think you compute the depth of this point and compare to the value of this point in the depth map. You can check out the point cloud projection code here: https://github.com/facebookresearch/sound-spaces/blob/0e87180459a5c9901bd1b17fe83405ebe57b9360/soundspaces/tasks/nav.py#L297-L329

**Comment by ChanganVR** [comment]
Normalization happens here: https://github.com/facebookresearch/habitat-lab/blob/0e1d2afe04b5856e6b5b3fc561adcea414091be4/habitat/sims/habitat_simulator/habitat_simulator.py#L158-L180

You can set the `NORMALIZE_DEPTH` attribute to False to avoid it.

**Comment by Yushi-Du** [comment]
Got it! It works!!
