### ISSUE TITLE
How to set check points (best_val.pth and best_val.pth)?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#54]
@ChanganVR 
Thank you, I appreciate your wonderful work.

I tried to rerun your **_savi_** experiments following the usage you wrote. I have 1 GPU.
I have questions as follows：
1) How to set label check points?

- Is it set by modifying RL.PPO.SCENE_MEMORY_TRANSFORMER.pretrained_path? 
- What is RL.PPO.SCENE_MEMORY_TRANSFORMER.pretrained_path set to?

2) How to use the check point you provided? Specifically, which configuration can be modified to use the check point you provided?
![image](https://user-images.githubusercontent.com/34536352/133736930-baf71657-68c4-4d1f-a9e3-d845b3c7d465.png)
3) How can I train from scratch to get these two check points similar to the one you provided?
- label_predictor.pth
- best_val.pth

4) How to set DDPPO.pretrained_weights check points in line 60 of the file ss_baselines/savi/config/semantic_audionav/savi.yaml?
5) I use PPO trainer. Do I need to modify the parameter configuration of DDPPO?

**Comment by ChanganVR** [comment]
hi @yyf17, below are my responses to your questions:

1. The pretrained SAVi with memory size 1 should be set here: https://github.com/facebookresearch/sound-spaces/blob/0e87180459a5c9901bd1b17fe83405ebe57b9360/ss_baselines/savi/config/semantic_audionav/savi.yaml#L60. I didn't use RL.PPO.SCENE_MEMORY_TRANSFORMER.pretrained_path.

2.  best_val.pth is the pretrained weights of the final SAVi model. Lable_predictor.pth is used for pretraining SAVi, the weights of which was not provided though. If you just want to evaluate the final SAVi model, update the pretrained_weights path in savi.yaml.

3. I think this page has provided enough information for reproducing results: https://github.com/facebookresearch/sound-spaces/tree/main/ss_baselines/savi. Let me know if you have more specific questions regarding training. 

4. This should be the best validation model from SAVi_pretraining. Or you can use best_val.pth from the provided weights.

5. If you run DDPPO with one GPU, it should behave like PPO. You don't need to modify anything else.

**Comment by yyf17** [comment]
Thank you.
