### ISSUE TITLE
Question about format of ambisonic RIRs

### ISSUE THREAD

**Issue by karreny** [facebookresearch/sound-spaces#58]
Thank you for releasing this great dataset! 

I was wondering if the second-order ambisonic RIR files are in ACN/SN3D B-format (I'd like to rotate it in arbitrary directions)?

**Comment by ChanganVR** [comment]
@karreny Yes. This ambisonic RIR files are in the B-format and you should be able to rotate them in arbitrary directions.

**Comment by karreny** [comment]
@ChanganVR To do the rotation, I’d need to know the type of B-format, including ordering of channels and normalization. Could you verify if it is FuMa or ACN/SN3D or ACN/N3D? Is there documentation for the binauralizer script that would provide this info? Thanks!

**Comment by ChanganVR** [comment]
Hi @karreny the format is ACN/N3D. The binauralizer is developed by a collaborator at FRL and I do not have documents for it. If you have specific questions regarding the binauralizer, I could ask for you.

**Comment by karreny** [comment]
Thanks for your help @ChanganVR! 

Looking into your code for loading the audio metadata, I was also wondering about the coordinate transformations shown here: 

https://github.com/facebookresearch/sound-spaces/blob/f11fef81db0c6b05d42fd062faa4929195de4ddf/soundspaces/utils.py#L17-L32. 

Is the reason for subtracting 1.5 that the simulated microphone is assumed to be at a different height from the camera sensor? Thanks again.

**Comment by ChanganVR** [comment]
The offset was just a difference between the coordinate frame used by the acoustic simulation and the coordinate frame used by Habitat. You don't need to worry about it.

**Comment by karreny** [comment]
Great, thanks for all of your help!
