### ISSUE TITLE
AttributeError: 'SoundSpaces' object has no attribute '_sim'

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#6]
1. when I run python scripts/cache_observations.py , an error occured as follows:
Caching Replica observations ...

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0926 15:13:51.761842 40370 AssetAttributesManager.cpp:122] Asset attributes (capsule3DSolid : capsule3DSolid_hemiRings_4_cylRings_1_segments_12_halfLen_0.75_useTexCoords_false_useTangents_false) created and registered.
I0926 15:13:51.761885 40370 AssetAttributesManager.cpp:122] Asset attributes (capsule3DWireframe : capsule3DWireframe_hemiRings_8_cylRings_1_segments_16_halfLen_1) created and registered.
I0926 15:13:51.761914 40370 AssetAttributesManager.cpp:122] Asset attributes (coneSolid : coneSolid_segments_12_halfLen_1.25_rings_1_useTexCoords_false_useTangents_false_capEnd_true) created and registered.
I0926 15:13:51.761930 40370 AssetAttributesManager.cpp:122] Asset attributes (coneWireframe : coneWireframe_segments_32_halfLen_1.25) created and registered.
I0926 15:13:51.761940 40370 AssetAttributesManager.cpp:122] Asset attributes (cubeSolid : cubeSolid) created and registered.
I0926 15:13:51.761946 40370 AssetAttributesManager.cpp:122] Asset attributes (cubeWireframe : cubeWireframe) created and registered.
I0926 15:13:51.761968 40370 AssetAttributesManager.cpp:122] Asset attributes (cylinderSolid : cylinderSolid_rings_1_segments_12_halfLen_1_useTexCoords_false_useTangents_false_capEnds_true) created and registered.
I0926 15:13:51.761986 40370 AssetAttributesManager.cpp:122] Asset attributes (cylinderWireframe : cylinderWireframe_rings_1_segments_32_halfLen_1) created and registered.
I0926 15:13:51.761996 40370 AssetAttributesManager.cpp:122] Asset attributes (icosphereSolid : icosphereSolid_subdivs_1) created and registered.
I0926 15:13:51.762004 40370 AssetAttributesManager.cpp:122] Asset attributes (icosphereWireframe : icosphereWireframe_subdivs_1) created and registered.
I0926 15:13:51.762017 40370 AssetAttributesManager.cpp:122] Asset attributes (uvSphereSolid : uvSphereSolid_rings_8_segments_16_useTexCoords_false_useTangents_false) created and registered.
I0926 15:13:51.762030 40370 AssetAttributesManager.cpp:122] Asset attributes (uvSphereWireframe : uvSphereWireframe_rings_16_segments_32) created and registered.
I0926 15:13:51.762037 40370 AssetAttributesManager.cpp:108] AssetAttributesManager::buildCtorFuncPtrMaps : Built default primitive asset templates : 12
W0926 15:13:51.762580 40370 ObjectAttributesManager.cpp:326] Cannot find ./data/objects or ./data/objects.phys_properties.json. Aborting parse.
I0926 15:13:51.762589 40370 PhysicsAttributesManager.cpp:39] File (./data/default.phys_scene_config.json) Based physics manager attributes created and registered.
I0926 15:13:51.762646 40370 StageAttributesManager.cpp:79] File (data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.ply) Based stage attributes created and registered.
I0926 15:13:51.762653 40370 Simulator.cpp:145] Loading navmesh from data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.navmesh
I0926 15:13:51.762989 40370 Simulator.cpp:147] Loaded.
I0926 15:13:51.763332 40370 SceneGraph.h:93] Created DrawableGroup: 
Renderer: GeForce RTX 2060/PCIe/SSE2 by NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 430.64
Using optional features:
    GL_ARB_ES2_compatibility
    GL_ARB_direct_state_access
    GL_ARB_get_texture_sub_image
    GL_ARB_invalidate_subdata
    GL_ARB_multi_bind
    GL_ARB_robustness
    GL_ARB_separate_shader_objects
    GL_ARB_texture_filter_anisotropic
    GL_ARB_texture_storage
    GL_ARB_texture_storage_multisample
    GL_ARB_vertex_array_object
    GL_KHR_debug
Using driver workarounds:
    no-forward-compatible-core-context
    no-layout-qualifiers-on-old-glsl
    nv-zero-context-profile-mask
    nv-implementation-color-read-format-dsa-broken
    nv-cubemap-inconsistent-compressed-image-size
    nv-cubemap-broken-full-compressed-image-query
    nv-compressed-block-size-in-bits
I0926 15:13:55.722658 40370 ResourceManager.cpp:302] ResourceManager::loadStage : Not loading semantic mesh
I0926 15:13:55.724828 40370 simulator.py:181] Loaded navmesh data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.navmesh
Traceback (most recent call last):
  File "scripts/cache_observations.py", line 159, in <module>
    main('replica')
  File "scripts/cache_observations.py", line 146, in main
    obs, rotation_index = simulator.step(None)
  File "scripts/cache_observations.py", line 83, in step
    sim_obs = self._sim.get_sensor_observations()
AttributeError: 'SoundSpaces' object has no attribute '_sim'
I0926 15:13:56.307615 40370 PhysicsManager.cpp:33] Deconstructing PhysicsManager
I0926 15:13:56.307637 40370 SemanticScene.h:41] Deconstructing SemanticScene
I0926 15:13:56.307670 40370 SceneManager.h:25] Deconstructing SceneManager
I0926 15:13:56.307674 40370 SceneGraph.h:26] Deconstructing SceneGraph
I0926 15:13:56.307956 40370 Sensor.h:81] Deconstructing Sensor
I0926 15:13:56.307973 40370 Sensor.h:81] Deconstructing Sensor
I0926 15:13:56.312932 40370 Renderer.cpp:34] Deconstructing Renderer
I0926 15:13:56.312947 40370 WindowlessContext.h:17] Deconstructing WindowlessContext
I0926 15:13:56.319006 40370 Simulator.cpp:46] Deconstructing Simulator

1. my enrionment as follows(I modify the version habitat_sim and habitat before install soundspaces :
python
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 23:10:56) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import habitat_sim
>>> import habitat
>>> habitat_sim.__version__
'0.1.6'
>>> habitat.__version__
'0.1.6'
>>> import sounspace
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sounspace'
>>> import sounspaces
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'sounspaces'
>>> import soundspaces
>>> soundspaces.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'soundspaces' has no attribute '__version__'
>>>

**Comment by ChanganVR** [comment]
Hi, if you look at setup.py, the requirement for habitat lab and sim is v0.1.5. Currently I haven't updated the APIs to match the latest habitat version, which I'm planning to do later but not right now. 

If you need features from the lastest habitat, you should go ahead and make changes by yourself, which should be relatively easy considering it's only updating APIs. If you're fine with using v0.1.5, please use that for now, I'll update the code once I have some time.

**Comment by krantiparida** [comment]
Hi Changan. Can you please keep this issue open until you fix the code? Thanks

**Comment by ChanganVR** [comment]
Hi Kranti, 

Thanks for the suggestion. I'll keep this issue open.

**Comment by AbdelrahmanYounes** [comment]
@yyf17 I'm facing the same problem could you please let me know whether you've updated the APIs or downgraded the Habitat version?

**Comment by AbdelrahmanYounes** [comment]
@ChanganVR I've updated some of the APIs in cache_observations.py file as following:
1- line 82: sim_obs = self.get_sensor_observations() instead of sim_obs = self._sim.get_sensor_observations()
2- lines 48-49: self.reset() instead of self._sim.close() and del self._sim
then I've gotten this when I tried to run the file again, 15:10:38.104046 26711 simulator.py:181] Loaded navmesh data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.navmesh
Simulator::gpuDevice: no OpenGL context.
Aborted (core dumped)

so, could you please let me know If my APIs replacements are corrcet and If yes how can I solve the no OpenGL context error. Thanks in advance.

**Comment by ChanganVR** [comment]
The OpenGL context is used by the Habitat simulator. By default, I use pre-rendered observations and need no rendering on the fly. So I replaced the simulator with a dummy simulator class and re-write all functions. When you update the APIs, please carefully check and make sure that you're not using or calling the Habitat simulator.

I'll be able to work on this and update the APIs in three days if you are unable to figure this out.

**Comment by ChanganVR** [comment]
@czha5168 I'm not getting your motivation for doing these attempts. If you git clone habitat-sim and habitat-lab, check out the v0.1.5 versions and compile, it should work properly right?

**Comment by czha5168** [comment]
> @czha5168 I'm not getting your motivation for doing these attempts. If you git clone habitat-sim and habitat-lab, check out the v0.1.5 versions and compile, it should work properly right?

Thanks for pointing it out, and yes, it would have been much easier doing this way. I will delete above my distracting messages.
