### ISSUE TITLE
DummySimulator has no attibute "pathfinder"

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#60]
Ｔhanks for this great work!
1) when validation set self.config.USE_RENDERED_OBSERVATIONS  = True ｉｎ　ｓａｖｉ，ｔhe following error occurred
![image](https://user-images.githubusercontent.com/34536352/134859650-261732fb-7e21-48ca-98a1-0603dde08fc0.png)
How to modify this？

**Comment by ChanganVR** [comment]
@yyf17 are you plotting top-down map? If you are, you should set this variable to False because plotting the top-down map requires the use of HabitatSim not the DummySimulator.

**Comment by yyf17** [comment]
Thank you.
