### ISSUE TITLE
Split correspondiing to Heard sound

### ISSUE THREAD

**Issue by spaul007** [facebookresearch/sound-spaces#64]
Hi @ChanganVR, 

Thanks for sharing this wonderful work. 
In the provided dataset for SAVi, test split contains episodes with unheard sound. Where can I find the split for heard sound? Or is there any other way to evaluate the performance of heard sound?

**Comment by ChanganVR** [comment]
@spaul007 sorry for the late reply. If you want to evaluate the performance on heard sound, you should basically reuse the sounds from training split, and thus ``heard``.
