### ISSUE TITLE
binaural audios received from facing forward and backward are different

### ISSUE THREAD

**Issue by ly-zhu** [facebookresearch/sound-spaces#68]
Hi  Changan, @ChanganVR 

I found that the binaural audios received from facing forward [L1, R1] and facing backward [L2, R2] are different. I meant the L1 and R2 are different. Arn't they should be the same? May I ask what's the possible reason for resulting these difference? Possibly the difference came from when generating the RIR or from generating binaural audios by ambisonic audio?

Thanks!

Best
Lingyu

**Comment by ChanganVR** [comment]
Hi @ly-zhu,

Yes, this is expected because of binaural audio is different from simple two-channel stereo audio due to the ear shapes and canals.

Changan
