### ISSUE TITLE
pretrained weights for distractor sound setting 

### ISSUE THREAD

**Issue by spaul007** [facebookresearch/sound-spaces#72]
Hi @ChanganVR,

Is it possible to provide the pretrained weights for semantic_audionav_distractor setting?

**Comment by ChanganVR** [comment]
@spaul007 what's your email? I can send it to you in the email.

**Comment by spaul007** [comment]
Thanks a lot.
spaul007@ucr.edu

**Comment by sreeharshaparuchur1** [comment]
Hi @spaul007 ,

If you have the weights with you, could you share them with me at venkata.surya@alumni.iiit.ac.in?

Also, please share the modifications you made (if any) to the code/config files to run SAVi in this distractor sound setting.
