### ISSUE TITLE
tensorboard event file

### ISSUE THREAD

**Issue by spaul007** [facebookresearch/sound-spaces#74]
Hi @ChanganVR,

Is it possible to provide the tensorboard event file for the SAVi training?

**Comment by spaul007** [comment]
Thanks a lot.
spaul007@ucr.edu

**Comment by sreeharshaparuchur1** [comment]
@ChanganVR, I would really appreciate if you could share the same with me as well. My email ID is venkata.surya@alumni.iiit.ac.in
