### ISSUE TITLE
About the difference between the soundspaces1.0 and soundspaces2.0

### ISSUE THREAD

**Issue by chenjinyubuaa** [facebookresearch/sound-spaces#76]
Hello! I am trying to use the soundspaces2.0. I am very happy to disuse the large RIR files.

 So I want to change the code in `soundspaces/simulator.py` to render discrete action spaces with the new rendering function 
 in `soundspaces/continuous_simulator.py`, without loading the files in `data/binaural_rirs/ `.  

Will it get same simulate result as the soundspace 1.0 ?

looking forward to you reply!

**Comment by ChanganVR** [comment]
@chenjinyubuaa , sorry for the delayed response. SoundSpaces 2.0 not only renders sound continuously, but also improves over the previous simulation quality, e.g., reverberation level accuracy and diffraction. So the simulation results won't be the same.
