### ISSUE TITLE
Issue with cache observations

### ISSUE THREAD

**Issue by drydenwiebe** [facebookresearch/sound-spaces#78]
Hello!

I am trying to setup this repository according to the instructions, and I keep running into this issue. When I run ```python scripts/cache_observations.py``` after downloading the contents of ```data/``` I get this issue:

```
I0714 17:06:11.358237  9579 Simulator.cpp:182] Simulator::reconfigure() : createSceneInstance success == true for active scene name : data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.ply with renderer.
I0714 17:06:11.383749 9579 simulator.py:221] Loaded navmesh data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.navmesh
Traceback (most recent call last):
  File "scripts/cache_observations.py", line 106, in <module>
    main('replica')
  File "scripts/cache_observations.py", line 90, in main
    simulator = Sim(episode_sim_config)
  File "/home/dryden/sound-spaces/soundspaces/simulator.py", line 149, in __init__
    self.add_acoustic_config()
  File "/home/dryden/sound-spaces/soundspaces/simulator.py", line 153, in add_acoustic_config
    acoustics_config = habitat_sim.sensor.RLRAudioPropagationConfiguration()
AttributeError: module 'habitat_sim.sensor' has no attribute 'RLRAudioPropagationConfiguration'
```

I was sure to install the specified versions of habitat-lab (v0.2.1) and habitat-sim (v0.2.1) but maybe a newer version is what is needed? After digging it seems that this RLRAudioPropagationConfiguration is fairly [new](https://github.com/facebookresearch/habitat-sim/blob/main/docs/AUDIO.md). 

I was wondering if anyone has ran into this before or has any ideas how to solve this?

Thanks!

**Comment by dosssman** [comment]
Hey there. I ran into a similar problem when trying to import a class from the `habitat_sim.sensor`.

I have built habitat-lab and habitat-sim at version 0.2.2.

My best guess is that soundspace library as of now using later version of habitat-sim and habitat-lab.

The simplest solution would probably be to install or build the latest version of habitat-sim and habitat-lab which the author seems to also be using. In those version ,the `habitat_sim.sensors` implements the missing attributes.

A workaround in case you want to stick to the 0.2.1 or 0.2.2 version would be to revert back the simulator.py code to use the `hsim_bindings` directly. For reference, please take a look at this [PR](https://github.com/dosssman/sound-spaces/pull/1/files).

Hope this can help to go past your problem.

**Comment by ChanganVR** [comment]
Hi @drydenwiebe, yes, I recently updated the API to remove hsim_bindings. Please use the latest main branch of Habitat-Sim. I'll update the installation instructions accordingly.

**Comment by drydenwiebe** [comment]
Thank you for your help.

I cloned and build habitat-lab and habitat-sim from their respective main branches (building habitat-sim using these [instructions](https://github.com/facebookresearch/habitat-sim/blob/main/BUILD_FROM_SOURCE.md) with no arguments to ```setup.py```). I was able to run the interactive demo for habitat-sim and it worked great.

However, when I try to run sound-spaces with this installation I get the following error:

```
[13:12:59:148444]:[Sim] Simulator.cpp(205)::reconfigure : CreateSceneInstance success == true for active scene name : data/scene_datasets/replica/apartment_0/habitat/mesh_semantic.ply  with renderer.
Traceback (most recent call last):
  File "scripts/cache_observations.py", line 106, in <module>
    main('replica')
  File "scripts/cache_observations.py", line 90, in main
    simulator = Sim(episode_sim_config)
  File "/home/dryden/sound-spaces/soundspaces/simulator.py", line 149, in __init__
    self.add_acoustic_config()
  File "/home/dryden/sound-spaces/soundspaces/simulator.py", line 154, in add_acoustic_config
    acoustics_config.threadCount = 1
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.RLRAudioPropagationConfiguration' object has no attribute 'threadCount'
```

It seems that I have somehow managed to build habitat-sim with ```RLRAudioPropagationConfiguration``` existing but not really supported. So, I then tried to build habitat-sim, with the ```--audio``` to the ```python setup.py install``` argument and I get a significantly worse error:

```
free(): invalid pointer
Aborted (core dumped)
```

@dosssman are you able to run ```scripts/cache_observations.py``` with habitat-lab and habitat-sim at v0.2.2? And if so, how exactly did you install those libraries to make it work (sorry for this question but I think details would help me)?

Thank you!

**Comment by dosssman** [comment]
Hello @drydenwiebe 

Which soundspaces script are you trying to run exactly ? Interactive demo ?
I managed to get it to run by installing habitat-lab and habitat-sim with version 2.0, but I did not try it with their respective main branch.

Regarding the "Invalid pointer", there is this workaround: instead of running `python -m habitat_sim.whatever_script`, I run `python src_python/whaterver_script.py` directly from the habit-sim root directory.

Regarding the cached observation script, since I only plan to use Soundspaces 2, I have skipped  most of the dataset downloads, so well as running the casched_observations. I can try to download them and run the script with v2.2.0 installed to see if it works

Hope this helps.

**Comment by drydenwiebe** [comment]
Hi @dosssman 

I am mostly interested in the corresponding audio-visual data for Replica and Matterport3D. But yes, I just wanted to run a demo to start and make sure I have everything setup. 

I was trying to run ```cache_observations.py``` when I got that error. If you could run it with sound spaces 2.0 that would be great!
 
 One other thing I would like to know is how exactly you installed habitat-sim (I think there is really only one way to install habitat-lab from the GitHub repo).
 
 @ChanganVR I guess if I want to run examples/cache_observations.py I should run sound-spaces from an older commit and use habitat-sim and habitat lab v0.1.7?
 
 Thanks!

**Comment by dosssman** [comment]
@drydenwiebe Hello there

I have also tried to run the cache observations script and it returned the invalid pointer.
I have also build the habitat-sim from source, using similar command to what you did:
`python setup.py install --audio --with-cuda` and also with `--headless` for my specific case.
Since you will only be using the parts of SS based on dataset, you might as well skip the `--audio` flag I think. Simpler for you to install from conda I think.

Now, regarding the invalid pointer error itself.
To the best of my knowledge, this happens when habitat-sim was compiled from source.
With this in mind, the work around that made the script run on my side was to comment the `import habitat_sim` line in the cache_observations.py script, and it seemed to work.

Hope it works.

**Comment by ChanganVR** [comment]
@drydenwiebe I updated the `cache_observations.py` file to account for the new changes. Let me know if it works for you know. You should be able to run it with the new Habitat version.

**Comment by drydenwiebe** [comment]
Seems to work great for ```scripts/cache_observations.py```

Interactive demo fails with a similar issue as I did not build with --audio this time:

```
  File "/home/dryden/sound-spaces/soundspaces/simulator.py", line 149, in __init__
    self.add_acoustic_config()
  File "/home/dryden/sound-spaces/soundspaces/simulator.py", line 154, in add_acoustic_config
    acoustics_config.threadCount = 1
AttributeError: 'habitat_sim._ext.habitat_sim_bindings.RLRAudioPropagationConfiguration' object has no attribute 'threadCount'
```

But for my current use case I think I am good to go. I am mostly interested with the audio-visual pairs for habitat and replica.

@dosssman thank you for your help as well!
