### ISSUE TITLE
Audio observations as raw sound files ?

### ISSUE THREAD

**Issue by dosssman** [facebookresearch/sound-spaces#79]
Dear @ChanganVR 

Thank you again for helping me out getting that missing file #77 in the last issue I opened.
After getting this, I have managed to get soundspace 2 to run and training the baseline DDPPO agent. :tada: 

Opening an issue might not be the best way to ask this, but I was wondering if soundspace can provide acoustic sensory data as raw audio signal instead of spectrogram.

Thaanks a lot for your time.
Best regards.

**Comment by ChanganVR** [comment]
Hi @dosssman, SoundSpaces computes waveforms initially, and depending on your sensor configuration (https://github.com/facebookresearch/sound-spaces/blob/4e400abaf65c7759a287355386dcd97de2b17e2b/configs/audionav/av_nav/mp3d/audiogoal.yaml#L24), it returns different observations accordingly. You can add `AUDIOGOAL_SENSOR` to the goal specification, which returns waveforms.

**Comment by dosssman** [comment]
Thanks a lot. I will play around with the other types of sensors to see if I get the desired output.
