### ISSUE TITLE
How to change batch size in your code?

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#8]
How to change batch size in your code?
Is this set by *.yaml file? I guess batch size is related with "RL.PPO.num_mini_batch",am I right?
1)partial yaml file of train
![image](https://user-images.githubusercontent.com/34536352/95044473-0df68e80-0712-11eb-92bc-8d48beced6fe.png)

2)partial yaml file of validation
![image](https://user-images.githubusercontent.com/34536352/95044411-eef7fc80-0711-11eb-861a-80c257ae55a6.png)

**Comment by ChanganVR** [comment]
Yes, batch size is related with "RL.PPO.num_mini_batch" and another parameter you can look into is the number of processes, which indicates how many environments are being trained simultaneously. The issue with that is Replica has only five big envionrments and increase the number of processes to be more than 5 would lead to an imbalance of environment sizes among processes. 

If you're concerned about the training time, maybe debug that first as I replied to you in the other issue, there might be something wrong with your GPU/pytorch or file I/O which leads to slow training.
