### ISSUE TITLE
How did you draw picture 8 in the article? 

### ISSUE THREAD

**Issue by yyf17** [facebookresearch/sound-spaces#9]
How did you draw picture 8 in the article? Can you give me a reference? Specifically include the following 3 points:
1) Grid
2) Response waveform diagram of position 1 and position 2
3) Red sound source
![image](https://user-images.githubusercontent.com/34536352/95823228-cdc18c80-0d5f-11eb-84a1-bc1851c59bc8.png)

Thank you.

**Comment by ChanganVR** [comment]
Hi Yinfeng, 

I didn't create this figure. My collaborator did. I believe what they did was loading the mesh files of these environments into MeshLab and plotting shapes (grids/waveform) from a top-down-view.
