### ISSUE TITLE
Wrong dims of depth_observations in SAVI

### ISSUE THREAD

**Issue by sivannavis** [facebookresearch/sound-spaces#90]
Hi @ChanganVR ! Hope you are doing great, and please bear with me for a series of questions!
When I train or evaluate SAVI model, there's an issue with the shape of depth observation:

The error during training looks like:

> Traceback (most recent call last):
>   File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/ext3/code/sound-spaces/ss_baselines/savi/run.py", line 144, in <module>
>     main()
>   File "/ext3/code/sound-spaces/ss_baselines/savi/run.py", line 107, in main
>     trainer.train()
>   File "/ext3/code/sound-spaces/ss_baselines/savi/ddppo/algo/ddppo_trainer.py", line 304, in train
>     rollouts.observations[sensor][0].copy_(batch[sensor])
> RuntimeError: output with shape [1, 128, 128, 1] doesn't match the broadcast shape [1, 128, 128, 128, 1]

The error during evaluation looks like:

> Traceback (most recent call last):
>   File "ss_baselines/savi/run.py", line 144, in <module>
>     main()
>   File "ss_baselines/savi/run.py", line 109, in main
>     trainer.eval(args.eval_interval, args.prev_ckpt_ind, config.USE_LAST_CKPT)
>   File "/ext3/code/sound-spaces/ss_baselines/common/base_trainer.py", line 105, in eval
>     result = self._eval_checkpoint(self.config.EVAL_CKPT_PATH_DIR, writer)
>   File "/ext3/code/sound-spaces/ss_baselines/savi/ppo/ppo_trainer.py", line 812, in _eval_checkpoint
>     _, actions, _, test_recurrent_hidden_states, test_em_features = self.actor_critic.act(
>   File "/ext3/code/sound-spaces/ss_baselines/savi/ppo/policy.py", line 52, in act
>     features, rnn_hidden_states, ext_memory_feats = self.net(
>   File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/ext3/code/sound-spaces/ss_baselines/savi/ppo/policy.py", line 381, in forward
>     x = self.get_features(observations, prev_actions)
>   File "/ext3/code/sound-spaces/ss_baselines/savi/ppo/policy.py", line 441, in get_features
>     x.append(self.visual_encoder(observations))
>   File "/ext3/miniconda3/envs/soundspaces/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/ext3/code/sound-spaces/ss_baselines/savi/models/smt_cnn.py", line 94, in forward
>     depth_observations = depth_observations.permute(0, 3, 1, 2)
> RuntimeError: number of dims don't match in permute

After inspecting the codes, I realize the problem happens when the observation is created with the shape of (num_process, 128,128,1,1) while both rollouts and smt_cnn models are expecting the depth shape to be (num_process, 128, 128, 1).

I couldn't find where to modify the depth observation shape, so my temporary workaround is to squeeze depth tensor within batch:

```
            if sensor == 'depth':
                # squeeze obs arrays
                obs[sensor] = np.squeeze(obs[sensor], axis=3)
```
https://github.com/facebookresearch/sound-spaces/blob/fb68e410a4a1388e2d63279e6b92b6f082371fec/ss_baselines/common/utils.py#L126-L153

Please let me know if I misunderstood anything or if there's a better solution! Thank you so much!

**Comment by sivannavis** [comment]
Also, I'm not sure how I should set the `NUM_PROCESSES` variable in the config file. I understand that it has to be greater or equal to num_mini_batch. Does it have to match the number of GPUs I'm using? I tried with 1 node, 1 GPU, and 2 processes, and it's still working. Could you help me clarify? Thanks!

**Comment by sreeharshaparuchur1** [comment]
Hey, regarding setting ```NUM_PROCESSES```, I beileve that [this issue](https://github.com/facebookresearch/sound-spaces/issues/46#issuecomment-901964493) as well as other tips that you might find helpful are discussed.

**Comment by sivannavis** [comment]
Hi @sreeharshaparuchur1, thanks for the comment! Yes, I've been referring to that thread, but still don't understand how I should set NUM_PROCESSES, as it will cause some problems in the validation period as I mentioned here https://github.com/facebookresearch/sound-spaces/issues/92#issuecomment-1238859105
Would you have any thoughts?
Thank you!

**Comment by ChanganVR** [comment]
NUM_PROCESSES is per GPU (training instance). When you run with multiple gpus, what happens is when you lauch distributed training with multiple parallel training instances, and EACH instance will create NUM_PROCESSES copies of the environments for training the policy on that instance. Gradients are then synced across all instances.
