### ISSUE TITLE
heard.pth vs unheard.pth

### ISSUE THREAD

**Issue by sreeharshaparuchur1** [facebookresearch/sound-spaces#96]
Hey,

As mentioned in your readme files, one can evaluate the pretrained av_wan code using either heard.pth or unheard.pth.
Could you elucidate upon what exactly the difference was in the creation of these two models and what performance disparity we can expect between models using the given weights?

Thank you.

**Comment by ChanganVR** [comment]
Hi @sreeharshaparuchur1, these two checkpoints are provided for two different experiments. Heard sound experiment : training and testing on the same telephone ringing sound and unheard sound experiment: training on multiple sounds and testing on unheard multiple sounds for evaluating generalization. Please check table 2 in the AV-WaN paper for more details.
