### ISSUE TITLE
test_multiple_unheard on Replica environment.

### ISSUE THREAD

**Issue by chenjinyubuaa** [facebookresearch/sound-spaces#98]
Hello! I try to test the av_wan model on the Replica environment. But the test_multiple_unheard split does not exist on the provided dataset link. I tried the unheard model on val_multiple_unheard split, and the SPL is 26 which is far from the accuracy in the paper(34). **So is the test_multiple_unheard split on Replica missing?**

**Comment by ChanganVR** [comment]
Hi @chenjinyubuaa I'm not sure why the split was missing but I reuploaded it here: https://drive.google.com/file/d/1vpeCJp6ZJTXbCrgjXt8M74RH847ZlYBH/view?usp=sharing.

**Comment by chenjinyubuaa** [comment]
Thank you!
